### ISSUE TITLE
Error encountered with juju secrets when using legacy mysql or mysql-root relations

### ISSUE THREAD

**Issue by shayancanonical** [canonical/mysql-k8s-operator#290]
## Steps to reproduce

1. juju deploy -n 1 mysql-k8s
2. juju deploy -n 1 mysql-test-app
3. juju relate mysql-k8s:mysql mysql-test-app:mysql

## Expected behavior
No errors, and both mysql-k8s and mysql-test-app switching to `active`

## Actual behavior
Encounter the following error trace with mysql-k8s in `error`:
```
unit-db23x1-0: 23:12:05 ERROR unit.db23x1/0.juju-log mysql:7: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-db23x1-0/charm/./src/charm.py", line 689, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-db23x1-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-db23x1-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-db23x1-0/charm/venv/ops/framework.py", line 344, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-db23x1-0/charm/venv/ops/framework.py", line 841, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-db23x1-0/charm/venv/ops/framework.py", line 930, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-db23x1-0/charm/src/relations/mysql.py", line 242, in _on_mysql_relation_created
    password = self._get_or_set_password_in_peer_secrets(username)
  File "/var/lib/juju/agents/unit-db23x1-0/charm/src/relations/mysql.py", line 69, in _get_or_set_password_in_peer_secrets
    self.charm.set_secret("app", password_key, password)
  File "/var/lib/juju/agents/unit-db23x1-0/charm/lib/charms/mysql/v0/mysql.py", line 639, in set_secret
    self._set_secret_in_juju(scope, key, value)
  File "/var/lib/juju/agents/unit-db23x1-0/charm/lib/charms/mysql/v0/mysql.py", line 606, in _set_secret_in_juju
    secret.set_content(content)
  File "/var/lib/juju/agents/unit-db23x1-0/charm/venv/ops/model.py", line 1157, in set_content
    self._validate_content(content)
  File "/var/lib/juju/agents/unit-db23x1-0/charm/venv/ops/model.py", line 1085, in _validate_content
    raise ValueError(
ValueError: Invalid secret keys: ['test123_password']. Keys should be lowercase letters and digits, at least 3 characters long, start with a letter, and not start or end with a hyphen.
```

## Versions

Operating system: Ubuntu 22.04

Juju CLI: 3.1.5

Juju agent: 3.1.5

Charm revision: 92

**Comment by paulomach** [comment]
not topical
